version: "3.8"

services:

  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: xlsx-uploader
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq_queue
    restart: always
    ports:
      - "5672:5672"  # Puerto AMQP para la conexión
      - "15672:15672" # UI de RabbitMQ (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongo_data: